name: Release
on:
  push:
    tags:
    - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create a release
      uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: true

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Publish to Github
      needs: release
      uses: gradle/gradle-build-action@v2.10.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        gradle-version: 8.5
        arguments: printVersion publishSvdparserPublicationToGitHubRepository
